version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
  chat_api:
    build:
      context: ./chat_api
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./chat_api:/opt/app
    depends_on:
      - db
  chat_frontend:
    build:
      context: ./chat_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./chat_frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - chat_api
